#include "SettingsPage.h"
#include "UI/Theme.h"
#include "App/AppPaths.h"
namespace vox {
static void settingsLabel(juce::Label&l,float s,juce::Colour c,bool b=false){l.setColour(juce::Label::textColourId,c);l.setFont(juce::Font(juce::FontOptions(s,b?juce::Font::bold:juce::Font::plain)));}
SettingsPage::SettingsPage(AudioEngine&e,SettingsManager&s):engine(e),settings(s){
 title.setText("Configuracoes",juce::dontSendNotification);subtitle.setText("Preferencias de interface, audio, desempenho, privacidade e backup.",juce::dontSendNotification);settingsLabel(title,24,theme::text,true);settingsLabel(subtitle,13,theme::muted);addAndMakeVisible(title);addAndMakeVisible(subtitle);settingsLabel(saveStatus,12,theme::green);saveStatus.setText("Alteracoes salvas",juce::dontSendNotification);addAndMakeVisible(saveStatus);
 restore.setButtonText("Restaurar tudo");restore.onClick=[this]{restoreDefaults();};addAndMakeVisible(restore);
 viewport.setViewedComponent(&canvas,false);viewport.setScrollBarsShown(true,false);addAndMakeVisible(viewport);
 setupCombo(themeBox,{"Escuro"},1);setupCombo(language,{"Portugues (Brasil)"},1);setupCombo(fontSize,{"Pequeno","Medio","Grande"},2);setupCombo(scale,{"100%","125%","150%","175%","200%"},1);
 setupCombo(quality,{"Baixa (44 kHz)","Alta (48 kHz)"},2);setupCombo(buffer,{"128 amostras","256 amostras","512 amostras","1024 amostras"},2);setupCombo(sampleRate,{"44100 Hz","48000 Hz"},2);setupCombo(audioMode,{"WASAPI compartilhado"},1);setupCombo(channels,{"Mono para estereo","Estereo"},1);
 setupCombo(processPriority,{"Normal","Alta"},2);setupCombo(meterRate,{"20 Hz","30 Hz","60 Hz"},2);setupCombo(logLevel,{"Erros","Normal","Detalhado"},2);setupCombo(updateChannel,{"Estavel"},1);
 setupToggle(compact,"Modo compacto",false);setupToggle(reduceAnimations,"Reduzir animacoes",false);setupToggle(showTips,"Mostrar dicas",true);setupToggle(autoContext,"Painel direito automatico",true);setupToggle(monitorInput,"Monitoramento",true);setupToggle(safetyLimiter,"Limitador de seguranca",engine.parameters().limiterEnabled.load());setupToggle(reconnect,"Reconexao automatica",true);setupToggle(syncDevices,"Sincronizar dispositivos",true);setupToggle(startWindows,"Iniciar com Windows",false);setupToggle(startMinimized,"Iniciar minimizado",false);setupToggle(startTray,"Iniciar na bandeja",false);setupToggle(restorePreset,"Restaurar ultimo preset",true);setupToggle(autoProcess,"Ligar processamento automaticamente",false);setupToggle(cpuOptimization,"Otimizacao de CPU",true);setupToggle(adaptiveQuality,"Qualidade adaptativa",false);setupToggle(economy,"Modo economia",false);setupToggle(highContrast,"Alto contraste",false);setupToggle(focusVisible,"Foco visivel",true);setupToggle(largeClick,"Maior area de clique",false);setupToggle(keyboardNav,"Navegacao por teclado",true);setupToggle(saveLogs,"Salvar logs",true);setupToggle(telemetry,"Telemetria (sempre desativada)",false);telemetry.setEnabled(false);setupToggle(autoUpdates,"Atualizacao automatica",false);
 juce::ComboBox* preferenceCombos[]{&themeBox,&language,&fontSize,&scale,&processPriority,&meterRate,&logLevel};for(auto*c:preferenceCombos)c->onChange=[this]{markDirty();};juce::ToggleButton* preferenceToggles[]{&compact,&reduceAnimations,&showTips,&autoContext,&cpuOptimization,&adaptiveQuality,&economy,&highContrast,&focusVisible,&largeClick,&keyboardNav,&saveLogs,&autoUpdates};for(auto*t:preferenceToggles)t->onClick=[this]{markDirty();};
 buffer.onChange=[this]{applyDevice(buffer.getText().getIntValue(),0);};sampleRate.onChange=[this]{applyDevice(0,sampleRate.getText().getDoubleValue());};quality.onChange=[this]{sampleRate.setSelectedId(quality.getSelectedId()==1?1:2,juce::sendNotificationSync);};safetyLimiter.onClick=[this]{engine.parameters().limiterEnabled=safetyLimiter.getToggleState();markDirty();};
 startWindows.onClick=[this]{const auto key="HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\ModificadorDeVoz";if(startWindows.getToggleState())juce::WindowsRegistry::setValue(key,"\""+juce::File::getSpecialLocation(juce::File::currentExecutableFile).getFullPathName()+"\"");else juce::WindowsRegistry::deleteValue(key);markDirty();};
 openDevices.setButtonText("Abrir pagina Dispositivos");openDevices.onClick=[this]{if(onOpenDevices)onOpenDevices();};exportButton.setButtonText("Exportar configuracoes");importButton.setButtonText("Importar configuracoes");openLogs.setButtonText("Abrir logs");clearLogs.setButtonText("Limpar logs");clearCache.setButtonText("Limpar cache");checkUpdates.setButtonText("Versao 1.0.0 - sem servidor de atualizacao");checkUpdates.setEnabled(false);backupButton.setButtonText("Criar backup local");for(auto*b:{&openDevices,&exportButton,&importButton,&openLogs,&clearLogs,&clearCache,&checkUpdates,&backupButton})canvas.addAndMakeVisible(b);
 exportButton.onClick=[this]{auto f=juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("ModificadorDeVoz-settings.json");f.replaceWithText(juce::JSON::toString(SettingsManager::parametersToJson(engine.parameters()),true));saveStatus.setText("Exportado para Documentos",juce::dontSendNotification);};importButton.onClick=[this]{auto f=juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("ModificadorDeVoz-settings.json");auto backup=AppPaths::data().getChildFile("settings-before-import.json");backup.replaceWithText(juce::JSON::toString(SettingsManager::parametersToJson(engine.parameters()),true));if(f.existsAsFile()&&SettingsManager::jsonToParameters(juce::JSON::parse(f),engine.parameters()))markDirty();else saveStatus.setText("Arquivo de importacao nao encontrado",juce::dontSendNotification);};openLogs.onClick=[]{AppPaths::logs().startAsProcess();};clearLogs.onClick=[](){for(auto&f:AppPaths::logs().findChildFiles(juce::File::findFiles,false,"*.log"))f.deleteFile();};clearCache.onClick=[](){for(auto&f:AppPaths::cache().findChildFiles(juce::File::findFilesAndDirectories,false))f.deleteRecursively();};backupButton.onClick=[this]{auto f=AppPaths::data().getChildFile("settings-backup-"+juce::Time::getCurrentTime().formatted("%Y%m%d-%H%M%S")+".json");f.replaceWithText(juce::JSON::toString(SettingsManager::parametersToJson(engine.parameters()),true));saveStatus.setText("Backup local criado",juce::dontSendNotification);};
 const juce::Array<juce::Component*> controls{&themeBox,&language,&fontSize,&scale,&compact,&reduceAnimations,&showTips,&autoContext,&quality,&buffer,&sampleRate,&audioMode,&channels,&monitorInput,&safetyLimiter,&reconnect,&syncDevices,&startWindows,&startMinimized,&startTray,&restorePreset,&autoProcess,&processPriority,&cpuOptimization,&adaptiveQuality,&meterRate,&economy,&highContrast,&focusVisible,&largeClick,&keyboardNav,&saveLogs,&logLevel,&telemetry,&updateChannel,&autoUpdates};for(auto*c:controls)canvas.addAndMakeVisible(c);
}
SettingsPage::~SettingsPage(){stopTimer();if(dirty)settings.save(engine.parameters());}
void SettingsPage::setupCombo(juce::ComboBox&c,const juce::StringArray&i,int selected){c.addItemList(i,1);c.setSelectedId(selected,juce::dontSendNotification);}void SettingsPage::setupToggle(juce::ToggleButton&t,const juce::String&n,bool state){t.setButtonText(n);t.setToggleState(state,juce::dontSendNotification);}void SettingsPage::markDirty(){dirty=true;saveStatus.setText("Salvando...",juce::dontSendNotification);startTimer(550);}void SettingsPage::timerCallback(){stopTimer();const bool ok=settings.save(engine.parameters());dirty=!ok;saveStatus.setText(ok?"Alteracoes salvas":"Nao foi possivel salvar",juce::dontSendNotification);saveStatus.setColour(juce::Label::textColourId,ok?theme::green:theme::red);}void SettingsPage::applyDevice(int block,double rate){auto setup=engine.deviceManager().getAudioDeviceSetup();if(block)setup.bufferSize=block;if(rate)setup.sampleRate=rate;auto error=engine.deviceManager().setAudioDeviceSetup(setup,true);if(error.isEmpty())markDirty();else{saveStatus.setText("Falha no audio: "+error,juce::dontSendNotification);saveStatus.setColour(juce::Label::textColourId,theme::red);}}void SettingsPage::restoreDefaults(){auto&p=engine.parameters();p.inputGainDb=0;p.outputGainDb=0;p.mix=1;p.pitchSemitones=0;p.fineCents=0;p.formant=0;p.noiseReduction=.25f;p.distortion=0;p.chorus=0;p.delay=0;p.reverb=0;p.ringMod=0;p.bitCrush=0;p.limiterEnabled=true;markDirty();}
void SettingsPage::paint(juce::Graphics&g){g.fillAll(theme::background);for(auto r:cards)theme::roundedPanel(g,r.toFloat(),12,theme::panel);const juce::StringArray names{"1. Interface","2. Audio","3. Dispositivos","4. Inicializacao","5. Desempenho","6. Acessibilidade","7. Privacidade e Logs","8. Atualizacoes e Backup"};for(int i=0;i<cards.size();++i){g.setColour(i%2?theme::cyan:theme::purple);g.setFont(juce::Font(juce::FontOptions(16,juce::Font::bold)));g.drawText(names[i],cards[i].reduced(16).removeFromTop(26),juce::Justification::centredLeft);}}
void SettingsPage::row(juce::Rectangle<int>&r,juce::Component&c){c.setBounds(r.removeFromTop(35).reduced(12,2));}void SettingsPage::layoutCard(int i,juce::Rectangle<int>r){r.removeFromTop(38);switch(i){case 0:row(r,themeBox);row(r,language);row(r,fontSize);row(r,scale);row(r,compact);row(r,reduceAnimations);row(r,showTips);row(r,autoContext);break;case 1:row(r,quality);row(r,sampleRate);row(r,buffer);row(r,audioMode);row(r,channels);row(r,monitorInput);row(r,safetyLimiter);break;case 2:row(r,reconnect);row(r,syncDevices);row(r,openDevices);break;case 3:row(r,startWindows);row(r,startMinimized);row(r,startTray);row(r,restorePreset);row(r,autoProcess);break;case 4:row(r,processPriority);row(r,cpuOptimization);row(r,adaptiveQuality);row(r,meterRate);row(r,economy);break;case 5:row(r,highContrast);row(r,focusVisible);row(r,largeClick);row(r,keyboardNav);break;case 6:row(r,telemetry);row(r,saveLogs);row(r,logLevel);row(r,openLogs);row(r,clearLogs);row(r,clearCache);break;case 7:row(r,updateChannel);row(r,autoUpdates);row(r,checkUpdates);row(r,exportButton);row(r,importButton);row(r,backupButton);break;}}
void SettingsPage::resized(){auto a=getLocalBounds().reduced(8);title.setBounds(a.getX(),0,260,34);subtitle.setBounds(a.getX(),32,620,22);saveStatus.setBounds(getWidth()-470,12,170,30);restore.setBounds(getWidth()-290,10,275,36);a.removeFromTop(60);viewport.setBounds(a);const int gap=12,w=(a.getWidth()-gap)/2,h=335;cards.clear();for(int row=0;row<4;++row)for(int col=0;col<2;++col)cards.add({8+col*(w+gap),8+row*(h+gap),w,h});canvas.setSize(a.getWidth()-14,8+4*(h+gap));for(int i=0;i<cards.size();++i)layoutCard(i,cards[i]);}
}
