#include "AudioEngine.h"
#include "App/AppPaths.h"
namespace vox {
AudioEngine::AudioEngine(){soundboardFormats.registerBasicFormats();soundboardReadAhead.startThread(juce::Thread::Priority::normal);startTimer(1500);}
AudioEngine::~AudioEngine(){stopTimer();stopSoundboard();soundboardTransport.setSource(nullptr);soundboardReadAhead.stopThread(3000);setMonitoring(false);devices.removeAudioCallback(this);saveDeviceState();devices.closeAudioDevice();}
juce::String AudioEngine::loadSoundboardFile(const juce::File&file){if(!file.existsAsFile())return "Arquivo não encontrado.";std::unique_ptr<juce::AudioFormatReader>reader(soundboardFormats.createReaderFor(file));if(!reader)return "Formato de áudio não suportado.";auto source=std::make_unique<juce::AudioFormatReaderSource>(reader.release(),true);const juce::ScopedLock lock(soundboardLock);soundboardTransport.stop();soundboardTransport.setSource(nullptr);soundboardReader=std::move(source);soundboardTransport.setSource(soundboardReader.get(),32768,&soundboardReadAhead,soundboardReader->getAudioFormatReader()->sampleRate);loadedSoundboardFile=file;soundboardPlaying=false;return {};}
void AudioEngine::playSoundboard(){const juce::ScopedLock lock(soundboardLock);if(!soundboardReader)return;soundboardTransport.setPosition(0);soundboardTransport.start();soundboardPlaying=true;}
void AudioEngine::stopSoundboard(){const juce::ScopedLock lock(soundboardLock);soundboardTransport.stop();soundboardTransport.setPosition(0);soundboardPlaying=false;}
double AudioEngine::soundboardPosition()const{const juce::ScopedLock lock(soundboardLock);return soundboardTransport.getCurrentPosition();}
double AudioEngine::soundboardDuration()const{const juce::ScopedLock lock(soundboardLock);return soundboardTransport.getLengthInSeconds();}
juce::String AudioEngine::soundboardFileName()const{const juce::ScopedLock lock(soundboardLock);return loadedSoundboardFile.getFileName();}
void AudioEngine::saveDeviceState(){if(auto state=devices.createStateXml())state->writeTo(AppPaths::data().getChildFile("audio-devices.xml"));if(auto state=monitorDevices.createStateXml())state->writeTo(AppPaths::data().getChildFile("monitor-device.xml"));}
juce::String AudioEngine::monitorDeviceName()const{auto*d=monitorDevices.getCurrentAudioDevice();return d?d->getName():juce::String();}
juce::String AudioEngine::setMonitoring(bool enabled){if(enabled==monitoring.load())return {};if(!enabled){monitoring=false;monitorDevices.removeAudioCallback(&monitorCallback);if(auto state=monitorDevices.createStateXml())state->writeTo(AppPaths::data().getChildFile("monitor-device.xml"));monitorDevices.closeAudioDevice();monitorFifo.reset();return {};}std::unique_ptr<juce::XmlElement> state;auto file=AppPaths::data().getChildFile("monitor-device.xml");if(file.existsAsFile())state=juce::XmlDocument::parse(file);auto result=monitorDevices.initialise(0,2,state.get(),true);if(result.isNotEmpty())return result;monitorFifo.reset();monitorDevices.addAudioCallback(&monitorCallback);monitoring=true;return {};}
void AudioEngine::MonitorCallback::audioDeviceAboutToStart(juce::AudioIODevice*){owner.monitorFifo.reset();}
void AudioEngine::MonitorCallback::audioDeviceIOCallbackWithContext(const float*const*,int,float*const*out,int channels,int samples,const juce::AudioIODeviceCallbackContext&){owner.renderMonitor(out,channels,samples);}
void AudioEngine::pushMonitor(const juce::AudioBuffer<float>&source,int samples)noexcept{if(!monitoring.load())return;int start1,size1,start2,size2;monitorFifo.prepareToWrite(samples,start1,size1,start2,size2);for(int c=0;c<2;++c){const float*src=source.getReadPointer(juce::jmin(c,source.getNumChannels()-1));if(size1>0)juce::FloatVectorOperations::copy(monitorRing.getWritePointer(c,start1),src,size1);if(size2>0)juce::FloatVectorOperations::copy(monitorRing.getWritePointer(c,start2),src+size1,size2);}monitorFifo.finishedWrite(size1+size2);}
void AudioEngine::renderMonitor(float*const*out,int channels,int samples)noexcept{for(int c=0;c<channels;++c)juce::FloatVectorOperations::clear(out[c],samples);int start1,size1,start2,size2;monitorFifo.prepareToRead(samples,start1,size1,start2,size2);for(int c=0;c<channels;++c){auto*dst=out[c];if(size1>0)juce::FloatVectorOperations::copy(dst,monitorRing.getReadPointer(juce::jmin(c,1),start1),size1);if(size2>0)juce::FloatVectorOperations::copy(dst+size1,monitorRing.getReadPointer(juce::jmin(c,1),start2),size2);}monitorFifo.finishedRead(size1+size2);}
juce::String AudioEngine::initialise(){
    auto file=AppPaths::data().getChildFile("audio-devices.xml");std::unique_ptr<juce::XmlElement> state;if(file.existsAsFile())state=juce::XmlDocument::parse(file);
    auto result=devices.initialise(1,2,state.get(),true,{},nullptr); if(result.isNotEmpty()){const juce::ScopedLock l(errorLock);error=result;return result;} devices.addAudioCallback(this);return {};
}
void AudioEngine::start(){running.store(true);} void AudioEngine::stop(){running.store(false);}
void AudioEngine::audioDeviceAboutToStart(juce::AudioIODevice*d){const int block=juce::jmax(maximumRealtimeBlockSize,d->getCurrentBufferSizeSamples());const int ch=juce::jmax(1,d->getActiveOutputChannels().countNumberOfSetBits());activeSampleRate.store(d->getCurrentSampleRate());preparedSamples.store(block);work.setSize(ch,block,false,true,false);soundboardBuffer.setSize(ch,block,false,true,false);soundboardTransport.prepareToPlay(block,d->getCurrentSampleRate());voice.prepare(d->getCurrentSampleRate(),block,ch);}
void AudioEngine::audioDeviceStopped(){preparedSamples.store(0);soundboardTransport.releaseResources();voice.reset();}
void AudioEngine::audioDeviceIOCallbackWithContext(const float*const*in,int ni,float*const*out,int no,int n,const juce::AudioIODeviceCallbackContext&){const auto begin=juce::Time::getHighResolutionTicks();for(int c=0;c<no;++c)juce::FloatVectorOperations::clear(out[c],n);const int channels=juce::jmin(work.getNumChannels(),juce::jmax(1,juce::jmax(ni,no)));if(channels<=0||n>preparedSamples.load()){xruns.fetch_add(1);return;}for(int c=0;c<channels;++c)juce::FloatVectorOperations::clear(work.getWritePointer(c),n);if(running.load()&&ni>0){for(int c=0;c<channels;++c){const float*src=in[juce::jmin(c,ni-1)];if(src)juce::FloatVectorOperations::copy(work.getWritePointer(c),src,n);}voice.process(work,n);}if(soundboardPlaying.load()&&soundboardLock.tryEnter()){soundboardBuffer.clear(0,n);juce::AudioSourceChannelInfo info(&soundboardBuffer,0,n);soundboardTransport.getNextAudioBlock(info);for(int c=0;c<channels;++c)work.addFrom(c,0,soundboardBuffer,juce::jmin(c,soundboardBuffer.getNumChannels()-1),0,n);if(!soundboardTransport.isPlaying())soundboardPlaying=false;soundboardLock.exit();}for(int c=0;c<no;++c)juce::FloatVectorOperations::copy(out[c],work.getReadPointer(juce::jmin(c,channels-1)),n);pushMonitor(work,n);const double elapsed=juce::Time::highResolutionTicksToSeconds(juce::Time::getHighResolutionTicks()-begin),allowed=n/activeSampleRate.load();cpu.store(allowed>0?elapsed/allowed:0);if(elapsed>allowed)xruns.fetch_add(1);}
void AudioEngine::timerCallback(){if(autoReconnect.load()&&devices.getCurrentAudioDevice()==nullptr)devices.restartLastAudioDevice();}
}
