#include "MainComponent.h"
namespace vox {
class MainComponent::ControlsPage final:public juce::Component{
public:
    ControlsPage(){setOpaque(true);}void paint(juce::Graphics&g)override{g.fillAll(juce::Colour(0xff181a20));}void resized()override{auto a=getLocalBounds().reduced(16);for(auto*c:controls)c->setBounds(a.removeFromTop(48).reduced(4));}
    void addSlider(const juce::String&name,double lo,double hi,double step,std::atomic<float>&v){auto*l=labels.add(new juce::Label({},name));l->setColour(juce::Label::textColourId,juce::Colours::white);auto*s=sliders.add(new juce::Slider(juce::Slider::LinearHorizontal,juce::Slider::TextBoxRight));s->setRange(lo,hi,step);s->setValue(v.load(),juce::dontSendNotification);s->onValueChange=[s,&v]{v.store((float)s->getValue());};addAndMakeVisible(l);addAndMakeVisible(s);controls.add(l);controls.add(s);}
    void addToggle(const juce::String&name,std::atomic<bool>&v){auto*b=toggles.add(new juce::ToggleButton(name));b->setToggleState(v.load(),juce::dontSendNotification);b->onClick=[b,&v]{v.store(b->getToggleState());};addAndMakeVisible(b);controls.add(b);}
    void addPresetUi(PresetManager&p,Parameters&params){combo=std::make_unique<juce::ComboBox>();combo->addItemList(p.names(),1);combo->setSelectedId(1);combo->onChange=[this,&p,&params]{p.load(combo->getText(),params);};addAndMakeVisible(*combo);controls.add(combo.get());auto*b=buttons.add(new juce::TextButton("Salvar como preset"));b->onClick=[this,&p,&params]{const auto name="Meu preset "+juce::Time::getCurrentTime().formatted("%Y%m%d-%H%M%S");p.save(name,params);combo->clear();combo->addItemList(p.names(),1);combo->setText(name,juce::dontSendNotification);};addAndMakeVisible(b);controls.add(b);}
private:juce::OwnedArray<juce::Label>labels;juce::OwnedArray<juce::Slider>sliders;juce::OwnedArray<juce::ToggleButton>toggles;juce::OwnedArray<juce::TextButton>buttons;juce::Array<juce::Component*>controls;std::unique_ptr<juce::ComboBox>combo;
};
class MainComponent::DiagnosticsPage final:public juce::Component,private juce::Timer{public:DiagnosticsPage(AudioEngine&e):engine(e){report.setMultiLine(true);report.setReadOnly(true);addAndMakeVisible(report);copy.onClick=[this]{juce::SystemClipboard::copyTextToClipboard(report.getText());};addAndMakeVisible(copy);startTimer(500);}void resized()override{auto a=getLocalBounds().reduced(12);copy.setBounds(a.removeFromBottom(36));report.setBounds(a);}void timerCallback()override{report.setText(DiagnosticsManager::report(engine),false);}private:AudioEngine&engine;juce::TextEditor report;juce::TextButton copy{"Copiar relatório"};};

MainComponent::MainComponent(AudioEngine&e,SettingsManager&s):engine(e),settings(s),devices(e.deviceManager(),0,1,0,2,true,true,true,false){
    setSize(980,700);voice=std::make_unique<ControlsPage>();cleanup=std::make_unique<ControlsPage>();dynamics=std::make_unique<ControlsPage>();effects=std::make_unique<ControlsPage>();presetPage=std::make_unique<ControlsPage>();diagnostics=std::make_unique<DiagnosticsPage>(e);auto&p=e.parameters();
    voice->addSlider("Pitch (semitons)",-12,12,.1,p.pitchSemitones);voice->addSlider("Ajuste fino (cents)",-100,100,1,p.fineCents);voice->addSlider("Formante",-1,1,.01,p.formant);voice->addSlider("Mistura",0,1,.01,p.mix);voice->addSlider("Ganho de entrada (dB)",-24,24,.1,p.inputGainDb);voice->addSlider("Ganho de saída (dB)",-24,24,.1,p.outputGainDb);voice->addToggle("Inverter fase",p.phaseInvert);
    cleanup->addToggle("Limpeza ativa",p.cleanupEnabled);cleanup->addSlider("Redução de ruído",0,1,.01,p.noiseReduction);cleanup->addSlider("Passa-altas (Hz)",20,2000,1,p.hpFreq);cleanup->addSlider("Passa-baixas (Hz)",2000,20000,10,p.lpFreq);cleanup->addToggle("Noise gate",p.gateEnabled);cleanup->addSlider("Gate threshold (dB)",-80,0,.1,p.gateThreshold);cleanup->addSlider("Gate attack (ms)",.1,200,.1,p.gateAttack);cleanup->addSlider("Gate release (ms)",1,2000,1,p.gateRelease);
    dynamics->addToggle("Compressor",p.compressorEnabled);dynamics->addSlider("Threshold (dB)",-60,0,.1,p.compressorThreshold);dynamics->addSlider("Ratio",1,20,.1,p.compressorRatio);dynamics->addSlider("Attack (ms)",.1,200,.1,p.compressorAttack);dynamics->addSlider("Release (ms)",1,2000,1,p.compressorRelease);dynamics->addToggle("Limitador final",p.limiterEnabled);
    effects->addSlider("Distorção",0,1,.01,p.distortion);effects->addSlider("Chorus",0,1,.01,p.chorus);effects->addSlider("Flanger",0,1,.01,p.flanger);effects->addSlider("Delay",0,1,.01,p.delay);effects->addSlider("Reverb",0,1,.01,p.reverb);effects->addSlider("Ring modulation",0,1,.01,p.ringMod);effects->addSlider("Bit crusher",0,1,.01,p.bitCrush);presetPage->addPresetUi(presets,p);
    const auto bg=juce::Colour(0xff20232b);tabs.addTab("Dispositivos",bg,&devices,false);tabs.addTab("Voz",bg,voice.get(),false);tabs.addTab("Limpeza",bg,cleanup.get(),false);tabs.addTab("Dinâmica",bg,dynamics.get(),false);tabs.addTab("Efeitos",bg,effects.get(),false);tabs.addTab("Presets",bg,presetPage.get(),false);tabs.addTab("Diagnóstico",bg,diagnostics.get(),false);addAndMakeVisible(tabs);
    start.onClick=[this]{if(engine.isRunning())engine.stop();else engine.start();};bypass.onClick=[&p]{p.bypass.store(!p.bypass.load());};mute.onClick=[&p]{p.muted.store(!p.muted.load());};addAndMakeVisible(start);addAndMakeVisible(bypass);addAndMakeVisible(mute);status.setColour(juce::Label::textColourId,juce::Colours::lightgreen);meter.setColour(juce::Label::textColourId,juce::Colours::white);addAndMakeVisible(status);addAndMakeVisible(meter);startTimerHz(20);
}
MainComponent::~MainComponent(){settings.save(engine.parameters());}
void MainComponent::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff101217));}
void MainComponent::resized(){auto a=getLocalBounds().reduced(10);auto top=a.removeFromTop(44);start.setBounds(top.removeFromLeft(110).reduced(3));bypass.setBounds(top.removeFromLeft(130).reduced(3));mute.setBounds(top.removeFromLeft(110).reduced(3));status.setBounds(top.removeFromLeft(210));meter.setBounds(top);tabs.setBounds(a);}
void MainComponent::timerCallback(){const bool on=engine.isRunning();start.setButtonText(on?"Parar":"Iniciar");mute.setButtonText(engine.parameters().muted.load()?"Reativar mic":"Silenciar");status.setText(on?(engine.parameters().muted.load()?"● Microfone silenciado":"● Processamento ativo"):"○ Processamento parado",juce::dontSendNotification);const auto in=engine.processor().inputPeak(),out=engine.processor().outputPeak();meter.setText("Entrada "+juce::String(juce::Decibels::gainToDecibels(in),1)+" dB | Saída "+juce::String(juce::Decibels::gainToDecibels(out),1)+" dB"+(out>=.999f?"  CLIP!":""),juce::dontSendNotification);}
}
