#include "MainComponent.h"
#include "Theme.h"
#include "App/AppPaths.h"
namespace vox {
static void styleLabel(juce::Label&l,float size,juce::Colour colour,bool bold=false){l.setColour(juce::Label::textColourId,colour);l.setFont(juce::Font(juce::FontOptions(size,bold?juce::Font::bold:juce::Font::plain)));}
class MainComponent::SettingsPage final:public juce::Component{
public:
 SettingsPage(AudioEngine&e,SettingsManager&s):engine(e),settings(s){
  title.setText("Configuracoes",juce::dontSendNotification);styleLabel(title,24,theme::text,true);subtitle.setText("Personalize o Modificador de Voz do seu jeito.",juce::dontSendNotification);styleLabel(subtitle,13,theme::muted);addAndMakeVisible(title);addAndMakeVisible(subtitle);
  restore.setButtonText("Restaurar todas as configuracoes");restore.onClick=[this]{auto&p=engine.parameters();p.inputGainDb=0;p.outputGainDb=0;p.mix=1;p.pitchSemitones=0;p.fineCents=0;p.formant=0;p.noiseReduction=.25f;p.distortion=0;p.chorus=0;p.delay=0;p.reverb=0;p.ringMod=0;p.bitCrush=0;settings.save(p);message.setText("Configuracoes restauradas.",juce::dontSendNotification);};addAndMakeVisible(restore);
  setupCombo(themeBox,{"Escuro"},1);setupCombo(language,{"Portugues (Brasil)"},1);setupCombo(fontSize,{"Pequeno","Medio","Grande"},2);setupCombo(quality,{"Baixa (44 kHz)","Alta (48 kHz)"},2);setupCombo(buffer,{"128 amostras","256 amostras","512 amostras","1024 amostras"},2);setupCombo(sampleRate,{"44100 Hz","48000 Hz"},2);
  buffer.onChange=[this]{applyDevice(buffer.getText().getIntValue(),0);};sampleRate.onChange=[this]{applyDevice(0,sampleRate.getText().getDoubleValue());};quality.onChange=[this]{sampleRate.setSelectedId(quality.getSelectedId()==1?1:2,juce::sendNotificationSync);};
  setupToggle(reduceAnimations,"Reduzir animacoes",false);setupToggle(monitorInput,"Monitoramento de entrada",true);setupToggle(reconnect,"Reconexao automatica",true);setupToggle(startWindows,"Iniciar com o Windows",false);setupToggle(startMinimized,"Iniciar minimizado",false);setupToggle(cpuOptimization,"Otimizacao de CPU",true);setupToggle(highContrast,"Alto contraste",false);setupToggle(focusVisible,"Foco visivel",true);setupToggle(compact,"Interface compacta",false);setupToggle(saveLogs,"Salvar logs de depuracao",true);
  startWindows.onClick=[this]{const auto key="HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\ModificadorDeVoz";if(startWindows.getToggleState())juce::WindowsRegistry::setValue(key,"\""+juce::File::getSpecialLocation(juce::File::currentExecutableFile).getFullPathName()+"\"");else juce::WindowsRegistry::deleteValue(key);};
  openDevices.setButtonText("Abrir configuracao de dispositivos");addAndMakeVisible(openDevices);openDevices.onClick=[this]{message.setText("Use a secao Dispositivos no menu lateral.",juce::dontSendNotification);};
  exportButton.setButtonText("Exportar configuracoes");importButton.setButtonText("Importar configuracoes");openLogs.setButtonText("Abrir pasta de logs");clearCache.setButtonText("Limpar cache");for(auto*b:{&exportButton,&importButton,&openLogs,&clearCache})addAndMakeVisible(b);
  exportButton.onClick=[this]{auto f=juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("ModificadorDeVoz-settings.json");f.replaceWithText(juce::JSON::toString(SettingsManager::parametersToJson(engine.parameters()),true));message.setText("Exportado para Documentos.",juce::dontSendNotification);};
  importButton.onClick=[this]{auto f=juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("ModificadorDeVoz-settings.json");if(f.existsAsFile()&&SettingsManager::jsonToParameters(juce::JSON::parse(f),engine.parameters()))message.setText("Configuracoes importadas.",juce::dontSendNotification);else message.setText("Arquivo de importacao nao encontrado.",juce::dontSendNotification);};
  openLogs.onClick=[]{AppPaths::logs().startAsProcess();};clearCache.onClick=[this]{auto d=AppPaths::cache();for(auto&f:d.findChildFiles(juce::File::findFilesAndDirectories,false))f.deleteRecursively();message.setText("Cache limpo.",juce::dontSendNotification);};styleLabel(message,12,theme::green);addAndMakeVisible(message);
 }
 void paint(juce::Graphics&g)override{g.fillAll(theme::background);for(auto r:cards){theme::roundedPanel(g,r.toFloat(),12,theme::panel);}const juce::StringArray names{"1. Interface","2. Audio","3. Dispositivos","4. Inicializacao","5. Desempenho","6. Acessibilidade / Logs"};for(int i=0;i<cards.size();++i){g.setColour(i%2?theme::cyan:theme::purple);g.setFont(juce::Font(juce::FontOptions(16,juce::Font::bold)));g.drawText(names[i],cards[i].reduced(18).removeFromTop(28),juce::Justification::centredLeft);}}
 void resized()override{auto a=getLocalBounds().reduced(8);title.setBounds(a.getX(),2,300,34);subtitle.setBounds(a.getX(),34,480,22);restore.setBounds(getWidth()-295,12,280,38);a.removeFromTop(62);const int gap=12,w=(a.getWidth()-gap)/2,h=(a.getHeight()-gap*2)/3;cards.clear();for(int row=0;row<3;++row)for(int col=0;col<2;++col)cards.add({a.getX()+col*(w+gap),a.getY()+row*(h+gap),w,h});layoutInterface(cards[0]);layoutAudio(cards[1]);layoutDevices(cards[2]);layoutStartup(cards[3]);layoutPerformance(cards[4]);layoutAccess(cards[5]);}
private:
 void setupCombo(juce::ComboBox&c,const juce::StringArray&items,int selected){c.addItemList(items,1);c.setSelectedId(selected,juce::dontSendNotification);addAndMakeVisible(c);}void setupToggle(juce::ToggleButton&t,const juce::String&name,bool state){t.setButtonText(name);t.setToggleState(state,juce::dontSendNotification);addAndMakeVisible(t);}void applyDevice(int block,double rate){auto setup=engine.deviceManager().getAudioDeviceSetup();if(block>0)setup.bufferSize=block;if(rate>0)setup.sampleRate=rate;auto result=engine.deviceManager().setAudioDeviceSetup(setup,true);message.setText(result.isEmpty()?"Audio atualizado.":"Falha: "+result,juce::dontSendNotification);}
 void row(juce::Rectangle<int>&r,juce::Component&c){c.setBounds(r.removeFromTop(38).reduced(14,3));}void layoutInterface(juce::Rectangle<int>r){r.removeFromTop(42);row(r,themeBox);row(r,reduceAnimations);row(r,language);row(r,fontSize);}void layoutAudio(juce::Rectangle<int>r){r.removeFromTop(42);row(r,quality);row(r,buffer);row(r,sampleRate);row(r,monitorInput);}void layoutDevices(juce::Rectangle<int>r){r.removeFromTop(42);row(r,reconnect);row(r,openDevices);row(r,message);}void layoutStartup(juce::Rectangle<int>r){r.removeFromTop(42);row(r,startWindows);row(r,startMinimized);}void layoutPerformance(juce::Rectangle<int>r){r.removeFromTop(42);row(r,cpuOptimization);row(r,compact);}void layoutAccess(juce::Rectangle<int>r){r.removeFromTop(42);row(r,highContrast);row(r,focusVisible);row(r,saveLogs);auto x=r.removeFromTop(38);exportButton.setBounds(x.removeFromLeft(x.getWidth()/2).reduced(5));importButton.setBounds(x.reduced(5));x=r.removeFromTop(38);openLogs.setBounds(x.removeFromLeft(x.getWidth()/2).reduced(5));clearCache.setBounds(x.reduced(5));}
 AudioEngine&engine;SettingsManager&settings;juce::Label title,subtitle,message;juce::TextButton restore,openDevices,exportButton,importButton,openLogs,clearCache;juce::ComboBox themeBox,language,fontSize,quality,buffer,sampleRate;juce::ToggleButton reduceAnimations,monitorInput,reconnect,startWindows,startMinimized,cpuOptimization,highContrast,focusVisible,compact,saveLogs;juce::Array<juce::Rectangle<int>>cards;
};
MainComponent::MainComponent(AudioEngine&e,SettingsManager&s):engine(e),settings(s),devices(e.deviceManager(),0,1,0,2,true,true,true,false){
 setLookAndFeel(&look);setSize(1450,900);addAndMakeVisible(sidebar);sidebar.onSelect=[this](int p){showPage(p);};sidebar.setSelected(1);
 title.setText("Modificador de Voz",juce::dontSendNotification);styleLabel(title,21,theme::text,true);version.setText("v1.0.0",juce::dontSendNotification);styleLabel(version,12,theme::muted);pageTitle.setText("Biblioteca de vozes",juce::dontSendNotification);styleLabel(pageTitle,23,theme::text,true);addAndMakeVisible(title);addAndMakeVisible(version);addAndMakeVisible(pageTitle);
 search.setTextToShowWhenEmpty("Pesquisar vozes e efeitos",theme::muted);search.setTooltip("Filtrar presets pelo nome");search.onTextChange=[this]{filterCards();};addAndMakeVisible(search);clearSearch.onClick=[this]{search.clear();};addAndMakeVisible(clearSearch);deviceStatus.setColour(juce::TextButton::buttonColourId,theme::panel);deviceStatus.onClick=[this]{showPage(5);};addAndMakeVisible(deviceStatus);
 const juce::StringArray tabNames{"Vozes","Efeitos","Painel de som","Favoritos"};for(int i=0;i<tabNames.size();++i){auto*b=tabs.add(new juce::TextButton(tabNames[i]));b->setColour(juce::TextButton::buttonColourId,i==0?theme::blue:juce::Colours::transparentBlack);b->onClick=[this,i]{if(i==0)showPage(1);else if(i==1)showPage(2);else notification.showMessage(i==2?"Painel de som em preparacao.":"Filtro de favoritos ativado.");};addAndMakeVisible(b);}
 bannerTitle.setText("Transforme sua voz em tempo real",juce::dontSendNotification);styleLabel(bannerTitle,24,theme::text,true);bannerText.setText("Escolha uma voz, ajuste os efeitos e utilize no Discord, FiveM ou OBS.",juce::dontSendNotification);styleLabel(bannerText,14,theme::text);configure.setColour(juce::TextButton::buttonColourId,theme::blue);configure.onClick=[this]{showPage(5);};addAndMakeVisible(bannerTitle);addAndMakeVisible(bannerText);addAndMakeVisible(configure);bannerTitle.setVisible(false);bannerText.setVisible(false);configure.setVisible(false);
 const juce::StringArray chipNames{"Todos","Naturais","Graves","Agudas","Robos","Terror","Criativas","Radio","Telefone","Jogos"};for(int i=0;i<chipNames.size();++i){auto*b=chips.add(new juce::TextButton(chipNames[i]));b->setColour(juce::TextButton::buttonColourId,i==0?theme::purple:theme::panel);b->onClick=[this,b]{categoryFilter=b->getButtonText();for(auto*c:chips)c->setColour(juce::TextButton::buttonColourId,c==b?theme::purple:theme::panel);filterCards();};addAndMakeVisible(b);}
 viewport.setViewedComponent(&cardCanvas,false);viewport.setScrollBarsShown(true,false);addAndMakeVisible(viewport);
 const juce::StringArray names{"Voz Limpa","Grave Profunda","Grave Suave","Aguda","Feminina Suave","Robo","Robo Pesado","Radio","Telefone","Megafone","Demonio","Monstro","Alienigena","Voz Metalica","Personagem Infantil","Narrador","Eco Espacial","Som Digital"};
 const juce::StringArray cats{"Naturais","Graves","Graves","Agudas","Naturais","Robos","Robos","Radio","Telefone","Criativas","Terror","Terror","Criativas","Robos","Agudas","Naturais","Criativas","Jogos"};
 for(int i=0;i<names.size();++i){auto*c=cards.add(new VoiceCardComponent(names[i],cats[i],i));c->onClick=[this,i]{applyPreset(i);};cardCanvas.addAndMakeVisible(c);}cards[0]->setSelected(true);
 const juce::StringArray effectNames{"Reverb","Delay","Chorus","Flanger","Distorcao","Bit Crusher","Ring Modulation","Radio","Telefone","Megafone","Eco Espacial","Som Metalico"};
 const juce::StringArray effectCats{"Espacial","Espacial","Modulacao","Modulacao","Distorcao","Criativo","Modulacao","Retro","Retro","Criativo","Espacial","Criativo"};
 for(int i=0;i<effectNames.size();++i){auto*c=effectCards.add(new VoiceCardComponent(effectNames[i],effectCats[i],i+2));c->setVisible(false);c->onClick=[this,i,c]{for(auto*e:effectCards)e->setSelected(e==c);auto&p=engine.parameters();if(i==0)p.reverb=juce::jmax(.5f,p.reverb.load());else if(i==1)p.delay=juce::jmax(.5f,p.delay.load());else if(i==2)p.chorus=juce::jmax(.5f,p.chorus.load());else if(i==3)p.flanger=juce::jmax(.5f,p.flanger.load());else if(i==4)p.distortion=juce::jmax(.5f,p.distortion.load());else if(i==5)p.bitCrush=juce::jmax(.5f,p.bitCrush.load());else if(i==6)p.ringMod=juce::jmax(.5f,p.ringMod.load());else presets.applyFactory(c->presetName(),p);selectedName.setText(c->presetName(),juce::dontSendNotification);selectedCategory.setText("Efeito ativo - "+c->presetCategory(),juce::dontSendNotification);notification.showMessage("Efeito ativado: "+c->presetName());};cardCanvas.addAndMakeVisible(c);}
 addAndMakeVisible(details);selectedName.setText(names[0],juce::dontSendNotification);selectedCategory.setText("Natural - Preset ativo",juce::dontSendNotification);styleLabel(selectedName,20,theme::text,true);styleLabel(selectedCategory,12,theme::muted);details.addAndMakeVisible(selectedName);details.addAndMakeVisible(selectedCategory);auto&p=e.parameters();addParameter("Intensidade / mistura",0,1,.01,p.mix);addParameter("Pitch",-12,12,.1,p.pitchSemitones);addParameter("Formante",-1,1,.01,p.formant);addParameter("Ganho de saida",-24,24,.1,p.outputGainDb);addParameter("Reverb",0,1,.01,p.reverb);addParameter("Distorcao",0,1,.01,p.distortion);savePreset.setColour(juce::TextButton::buttonColourId,theme::blue);savePreset.onClick=[this]{presets.save(selectedName.getText(),engine.parameters());notification.showMessage("Configuracoes salvas.");};duplicatePreset.onClick=[this]{presets.save(selectedName.getText()+" - copia",engine.parameters());notification.showMessage("Preset duplicado.");};resetPreset.onClick=[this]{applyPreset(selectedCard);notification.showMessage("Preset restaurado.");};for(auto*b:{&savePreset,&duplicatePreset,&resetPreset})details.addAndMakeVisible(b);
 addAndMakeVisible(devices);devices.setVisible(false);settingsPage=std::make_unique<SettingsPage>(engine,settings);addAndMakeVisible(*settingsPage);settingsPage->setVisible(false);diagnosticText.setMultiLine(true);diagnosticText.setReadOnly(true);diagnosticText.setColour(juce::TextEditor::backgroundColourId,theme::panel);addAndMakeVisible(diagnosticText);diagnosticText.setVisible(false);copyDiagnostic.onClick=[this]{juce::SystemClipboard::copyTextToClipboard(diagnosticText.getText());notification.showMessage("Relatorio copiado.");};addAndMakeVisible(copyDiagnostic);copyDiagnostic.setVisible(false);
 power.setColour(juce::TextButton::buttonColourId,theme::blue);power.onClick=[this]{engine.isRunning()?engine.stop():engine.start();notification.showMessage(engine.isRunning()?"Modificador de voz ativado.":"Modificador de voz desativado.");};mute.onClick=[&p,this]{p.muted=!p.muted.load();notification.showMessage(p.muted.load()?"Microfone silenciado.":"Microfone reativado.");};bypass.onClick=[&p]{p.bypass=!p.bypass.load();};monitor.setTooltip("O monitor depende do dispositivo de saida selecionado");monitor.onClick=[this]{notification.showMessage("Monitoramento usa a saida selecionada.");};for(auto*b:{&power,&monitor,&mute,&bypass})addAndMakeVisible(b);addAndMakeVisible(meter);styleLabel(status,13,theme::text,true);styleLabel(cpuLatency,12,theme::muted);styleLabel(deviceName,12,theme::muted);addAndMakeVisible(status);addAndMakeVisible(cpuLatency);addAndMakeVisible(deviceName);addChildComponent(notification);startTimerHz(30);
}
MainComponent::~MainComponent(){stopTimer();settings.save(engine.parameters());setLookAndFeel(nullptr);}
void MainComponent::addParameter(const juce::String&name,double lo,double hi,double step,std::atomic<float>&value){auto*l=parameterLabels.add(new juce::Label({},name));styleLabel(*l,13,theme::muted);auto*s=parameterSliders.add(new juce::Slider(juce::Slider::LinearHorizontal,juce::Slider::TextBoxRight));s->setRange(lo,hi,step);s->setValue(value.load(),juce::dontSendNotification);s->setTooltip(name);s->onValueChange=[s,&value]{value.store((float)s->getValue());};details.addAndMakeVisible(l);details.addAndMakeVisible(s);}
void MainComponent::showPage(int p){currentPage=p;sidebar.setSelected(p);const bool library=p==0||p==1||p==2||p==3||p==4||p==6;devices.setVisible(p==5);settingsPage->setVisible(p==8);diagnosticText.setVisible(p==7);copyDiagnostic.setVisible(p==7);viewport.setVisible(library);details.setVisible(library);for(auto*c:cards)c->setVisible(library&&p!=2);for(auto*c:effectCards)c->setVisible(library&&p==2);bannerTitle.setVisible(false);bannerText.setVisible(false);configure.setVisible(false);for(auto*b:tabs)b->setVisible(library);for(int i=0;i<tabs.size();++i)tabs[i]->setColour(juce::TextButton::buttonColourId,i==(p==2?1:0)?theme::blue:juce::Colours::transparentBlack);for(auto*b:chips)b->setVisible(library);const juce::StringArray names{"Visao geral","Biblioteca de Vozes","Biblioteca de Efeitos","Painel de Som","Equalizador","Dispositivos","Presets","Diagnostico","Configuracoes"};pageTitle.setText(names[p],juce::dontSendNotification);pageTitle.setVisible(p!=8);categoryFilter="Todos";filterCards();resized();repaint();}
void MainComponent::applyPreset(int i){selectedCard=i;for(int n=0;n<cards.size();++n)cards[n]->setSelected(n==i);const auto name=cards[i]->presetName();juce::String factory=name;if(name=="Voz Limpa")factory="Voz normal limpa";else if(name=="Grave Profunda"||name=="Grave Suave")factory="Masculina grave";else if(name=="Aguda")factory="Personagem infantil";else if(name=="Robo Pesado"||name=="Voz Metalica"||name=="Som Digital")factory="Robô";else if(name=="Radio")factory="Rádio policial";else if(name=="Eco Espacial")factory="Alienígena";presets.load(factory,engine.parameters());selectedName.setText(name,juce::dontSendNotification);selectedCategory.setText("Preset aplicado ao processamento",juce::dontSendNotification);auto&p=engine.parameters();const float values[]{p.mix.load(),p.pitchSemitones.load(),p.formant.load(),p.outputGainDb.load(),p.reverb.load(),p.distortion.load()};for(int n=0;n<parameterSliders.size();++n)parameterSliders[n]->setValue(values[n],juce::dontSendNotification);notification.showMessage("Preset carregado: "+name);}
void MainComponent::filterCards(){const auto q=search.getText().trim();int visible=0;auto filter=[&](VoiceCardComponent*c,bool page){const bool textOk=q.isEmpty()||c->presetName().containsIgnoreCase(q);const bool catOk=categoryFilter=="Todos"||c->presetCategory().containsIgnoreCase(categoryFilter);c->setVisible(page&&textOk&&catOk);if(c->isVisible())++visible;};for(auto*c:cards)filter(c,currentPage!=2);for(auto*c:effectCards)filter(c,currentPage==2);cardCanvas.setSize(juce::jmax(400,viewport.getWidth()-12),juce::jmax(viewport.getHeight(),((visible+4)/5)*170));resized();}
void MainComponent::paint(juce::Graphics&g){
 g.fillAll(theme::background);g.setColour(theme::secondary);g.fillRect(topBounds);g.setColour(theme::border);g.drawLine(0,(float)topBounds.getBottom(),(float)getWidth(),(float)topBounds.getBottom());
 juce::ColourGradient logoGrad(theme::cyan,{20.0f,22.0f},theme::purple,{52.0f,52.0f},false);g.setGradientFill(logoGrad);for(int i=0;i<7;++i){const float h=12.0f+std::abs(3-i)*-1.8f+((i%2)*12.0f);g.fillRoundedRectangle(22.0f+i*5.0f,36.0f-h*.5f,3.0f,h,1.5f);}
 if(details.isVisible()){theme::roundedPanel(g,rightBounds.toFloat().reduced(4),12,theme::panel);g.setColour(theme::border);g.drawLine((float)rightBounds.getX(),(float)rightBounds.getY()+64,(float)rightBounds.getRight(),(float)rightBounds.getY()+64);}
 g.setColour(theme::secondary);g.fillRect(bottomBounds);g.setColour(theme::border);g.drawLine(0,(float)bottomBounds.getY(),(float)getWidth(),(float)bottomBounds.getY());
 auto voiceCard=bottomBounds.removeFromLeft(245).toFloat().reduced(10,8);g.setColour(theme::panel);g.fillRoundedRectangle(voiceCard,10);g.setColour(theme::cyan);g.drawRoundedRectangle(voiceCard,10,1);g.drawEllipse(voiceCard.getX()+10,voiceCard.getCentreY()-22,44,44,2);g.drawLine(voiceCard.getX()+32,voiceCard.getCentreY()-12,voiceCard.getX()+32,voiceCard.getCentreY()+12,2);
}
void MainComponent::resized(){
 auto all=getLocalBounds();topBounds=all.removeFromTop(72);bottomBounds=all.removeFromBottom(88);
 auto sideArea=all.removeFromLeft(170);sidebar.setBounds(sideArea);
 title.setBounds(64,12,230,28);version.setBounds(66,39,80,18);
 search.setBounds(330,16,juce::jlimit(280,430,getWidth()/3),38);clearSearch.setBounds(search.getRight()-68,19,64,31);
 deviceStatus.setBounds(getWidth()-165,16,145,38);pageTitle.setBounds(all.getX()+18,82,330,34);
 contentBounds=all.reduced(14);contentBounds.removeFromTop(44);rightBounds=contentBounds.removeFromRight(getWidth()<1220?0:305);
 if(rightBounds.isEmpty())details.setVisible(false);else if(currentPage!=5&&currentPage!=7&&currentPage!=8)details.setVisible(true);
 auto work=contentBounds;auto tabArea=work.removeFromTop(42);for(auto*b:tabs)b->setBounds(tabArea.removeFromLeft(122).reduced(3));
 bannerBounds={};bannerTitle.setBounds({});bannerText.setBounds({});configure.setBounds({});
 chipBounds=work.removeFromTop(52);for(auto*b:chips){const int w=juce::jmax(64,b->getButtonText().length()*8+22);b->setBounds(chipBounds.removeFromLeft(w).reduced(3,8));}
 viewport.setBounds(work.reduced(2));int columns=juce::jlimit(3,7,juce::jmax(3,viewport.getWidth()/145));int cardW=juce::jmax(120,(viewport.getWidth()-18-(columns-1)*9)/columns),x=8,y=8,col=0;
 auto place=[&](VoiceCardComponent*c){if(!c->isVisible())return;c->setBounds(x,y,cardW,158);if(++col>=columns){col=0;x=8;y+=167;}else x+=cardW+9;};for(auto*c:cards)place(c);for(auto*c:effectCards)place(c);
 cardCanvas.setSize(juce::jmax(400,viewport.getWidth()-15),juce::jmax(viewport.getHeight(),y+168));
 details.setBounds(rightBounds);auto d=details.getLocalBounds().reduced(16);selectedName.setBounds(d.removeFromTop(32));selectedCategory.setBounds(d.removeFromTop(22));d.removeFromTop(12);
 for(int i=0;i<parameterSliders.size();++i){parameterLabels[i]->setBounds(d.removeFromTop(20));parameterSliders[i]->setBounds(d.removeFromTop(38));d.removeFromTop(2);}savePreset.setBounds(d.removeFromTop(38));d.removeFromTop(6);auto actions=d.removeFromTop(38);duplicatePreset.setBounds(actions.removeFromLeft(actions.getWidth()/2).reduced(2));resetPreset.setBounds(actions.reduced(2));
 auto fullContent=contentBounds.getUnion(rightBounds);devices.setBounds(fullContent.reduced(8));if(settingsPage)settingsPage->setBounds(fullContent.reduced(4));diagnosticText.setBounds(fullContent.reduced(8).withTrimmedBottom(46));copyDiagnostic.setBounds(fullContent.removeFromBottom(40).removeFromRight(190).reduced(3));
 auto btm=bottomBounds.reduced(18,9);deviceName.setBounds(btm.removeFromLeft(245));power.setBounds(btm.removeFromLeft(78).reduced(2));monitor.setBounds(btm.removeFromLeft(108).reduced(4));mute.setBounds(btm.removeFromLeft(104).reduced(4));bypass.setBounds(btm.removeFromLeft(88).reduced(4));meter.setBounds(btm.removeFromLeft(190).reduced(7,12));status.setBounds(btm.removeFromLeft(190));cpuLatency.setBounds(btm);notification.setBounds(getWidth()-385,82,350,54);
}
void MainComponent::timerCallback(){const auto in=engine.processor().inputPeak(),out=engine.processor().outputPeak();meter.setLevels(in,out);auto*d=engine.deviceManager().getCurrentAudioDevice();deviceName.setText(d?"Entrada: "+d->getName():"Dispositivo indisponivel",juce::dontSendNotification);deviceStatus.setButtonText(d?"Conectado":"Sem audio");deviceStatus.setColour(juce::TextButton::buttonColourId,d?theme::panel:theme::red.darker(.3f));power.setButtonText(engine.isRunning()?"DESLIGAR":"LIGAR");mute.setButtonText(engine.parameters().muted.load()?"REATIVAR":"SILENCIAR");status.setText(engine.isRunning()?(engine.parameters().muted.load()?"Microfone silenciado":"Modificador ativo"):"Modificador desligado",juce::dontSendNotification);status.setColour(juce::Label::textColourId,engine.isRunning()?theme::green:theme::muted);double latency=0;if(d&&d->getCurrentSampleRate()>0)latency=1000.0*(d->getInputLatencyInSamples()+d->getOutputLatencyInSamples()+d->getCurrentBufferSizeSamples())/d->getCurrentSampleRate();cpuLatency.setText("CPU "+juce::String(engine.cpuUsage()*100,1)+"%  -  "+(d?juce::String(latency,1)+" ms":"Latencia indisponivel"),juce::dontSendNotification);if(currentPage==7)diagnosticText.setText(DiagnosticsManager::report(engine),false);}
}
