#include "ModernComponents.h"
namespace vox {
void AudioLevelMeter::paint(juce::Graphics&g){auto r=getLocalBounds().toFloat();g.setColour(theme::border);g.fillRoundedRectangle(r,4);const auto draw=[&](float level,juce::Rectangle<float>a){auto f=juce::jlimit(0.0f,1.0f,std::sqrt(level));g.setColour(f>.96f?theme::red:(f>.75f?theme::yellow:theme::green));g.fillRoundedRectangle(a.withWidth(a.getWidth()*f),3);};draw(in,r.removeFromTop(r.getHeight()*.45f).reduced(2));draw(out,r.reduced(2));}
VoiceCardComponent::VoiceCardComponent(juce::String n,juce::String c,int i):juce::Button(n),name(std::move(n)),category(std::move(c)),colourIndex(i){setTooltip("Aplicar preset "+name);setWantsKeyboardFocus(true);}
void VoiceCardComponent::paintButton(juce::Graphics&g,bool hover,bool down){auto r=getLocalBounds().toFloat().reduced(4);g.setColour(selected?theme::elevated.brighter(.08f):(hover?theme::elevated:theme::panel));g.fillRoundedRectangle(r,14);g.setColour(selected?theme::cyan:theme::border);g.drawRoundedRectangle(r,14,selected?2.0f:1.0f);auto avatar=juce::Rectangle<float>(r.getCentreX()-30.0f,r.getY()+15.0f,60.0f,60.0f);const juce::Colour colours[]{theme::blue,theme::purple,theme::cyan,theme::green,theme::yellow};g.setGradientFill(juce::ColourGradient(colours[colourIndex%5],avatar.getTopLeft(),colours[(colourIndex+1)%5].darker(.4f),avatar.getBottomRight(),false));g.fillEllipse(avatar);g.setColour(theme::background.withAlpha(.7f));g.fillEllipse(avatar.reduced(12));juce::Path wave;for(int i=0;i<5;++i){float x=avatar.getX()+17.0f+i*7.0f,h=10.0f+(i%3)*8.0f;wave.startNewSubPath(x,avatar.getCentreY()-h*.5f);wave.lineTo(x,avatar.getCentreY()+h*.5f);}g.setColour(theme::text);g.strokePath(wave,juce::PathStrokeType(3,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));if(selected){g.setColour(theme::cyan);g.fillEllipse(r.getRight()-26,r.getY()+9,18,18);g.setColour(theme::background);g.setFont(juce::Font(juce::FontOptions(9,juce::Font::bold)));g.drawText("OK",(int)r.getRight()-26,(int)r.getY()+9,18,18,juce::Justification::centred);}g.setColour(theme::text);g.setFont(juce::Font(juce::FontOptions(14,juce::Font::bold)));g.drawFittedText(name,r.withTrimmedTop(82).withTrimmedBottom(22).toNearestInt(),juce::Justification::centred,2);g.setColour(theme::muted);g.setFont(12);g.drawText(category,r.removeFromBottom(24).toNearestInt(),juce::Justification::centred);if(down){g.setColour(theme::background.withAlpha(.18f));g.fillRoundedRectangle(getLocalBounds().toFloat().reduced(6),12);}}
SidebarComponent::SidebarComponent(){const juce::StringArray labels{"Inicio","Vozes","Efeitos","Painel de Som","Equalizador","Dispositivos","Presets","Diagnostico","Configuracoes"};for(int i=0;i<labels.size();++i){auto*b=buttons.add(new juce::TextButton(labels[i]));b->setTooltip(labels[i]);b->setColour(juce::TextButton::buttonColourId,juce::Colours::transparentBlack);b->setColour(juce::TextButton::textColourOffId,theme::muted);b->setColour(juce::TextButton::textColourOnId,theme::text);b->onClick=[this,i]{if(onSelect)onSelect(i);};addAndMakeVisible(b);}}
void SidebarComponent::setSelected(int i){selected=i;for(int n=0;n<buttons.size();++n)buttons[n]->setColour(juce::TextButton::buttonColourId,n==i?theme::blue:juce::Colours::transparentBlack);repaint();}
void SidebarComponent::resized(){auto a=getLocalBounds().reduced(12,18);for(auto*b:buttons){b->setBounds(a.removeFromTop(48).reduced(2));a.removeFromTop(5);}}
void SidebarComponent::paint(juce::Graphics&g){g.fillAll(theme::secondary);g.setColour(theme::border);g.drawLine((float)getWidth()-1,0,(float)getWidth()-1,(float)getHeight());g.setColour(theme::cyan);g.fillRoundedRectangle(0.0f,20.0f+selected*53.0f,4.0f,42.0f,2.0f);}
NotificationComponent::NotificationComponent(){setInterceptsMouseClicks(false,false);setVisible(false);}
void NotificationComponent::showMessage(const juce::String&m,bool e){message=m;colour=e?theme::red:theme::green;setVisible(true);toFront(false);startTimer(e?6000:2400);repaint();}
void NotificationComponent::timerCallback(){stopTimer();setVisible(false);}
void NotificationComponent::paint(juce::Graphics&g){g.setColour(theme::elevated);g.fillRoundedRectangle(getLocalBounds().toFloat(),10);g.setColour(colour);g.fillRoundedRectangle(0,0,5.0f,(float)getHeight(),2);g.setColour(theme::text);g.setFont(14);g.drawFittedText(message,getLocalBounds().reduced(16,8),juce::Justification::centredLeft,2);}
}
